name: MultiUse
main: com.enjin.angelcraftonomy.MultiUseCore
version: 1.0
author: UsuriousAngel
commands:
   MultiUse:
      description: MultiUse root command
      aliases: [mu]
permissions:
   multiuse.canswear:
      description: Allows a player to swear in chat
   multiuse.command.reload:
      description: Allows a player to reload the plugin
   multiuse.command.clear:
      description: Allows a player to clear the chat
   multiuse.command.restart:
      description: Allows a player to restart the server
   multiuse.command.giveaway:
      description: Allows a player to give a random player a reward
   multiuse.command.console:
      description: Allows a player to enter a command as the console 
   multiuse.command.gamemode:
      description: Allows use of the gamemode command
   multiuse.command.gamemode.creative:
      description: Allows use of the gamemode command
   multiuse.command.gamemode.survival:
      description: Allows use of the gamemode command
   multiuse.command.gamemode.spectator:
      description: Allows use of the gamemode command  
   multiuse.command.clearall:
      description: Clears all players chat 
   multiuse.command.maze:
      description: Generates a maze
   multiuse.command.aution:
      description: launches a firework in a peewee herman word of the day sort of way.
   multiuse.*:
      description: Gives access to all MultiUse commands/functions.
      children:
         multiuse.canswear: true
         multiuse.command.reload: true
         multiuse.command.clear: true
         multiuse.command.restart: true
         multiuse.command.giveaway: true
         multiuse.command.console: true
         multiuse.command.gamemode: true
         multiuse.command.gamemode.survival: true
         multiuse.command.gamemode.creative: true
         multiuse.command.gamemode.spectator: true
         multiuse.command.clearall: true
         multiuse.command.maze: true
         multiuse.command.aution: true
